In [ ]:
import rawpy
import cv2
from PIL import Image
import numpy as np
from multiprocessing.pool import Pool
import utils
import os


###############################################################################
# Instantiation
###############################################################################
lum_downsample = utils.Downsampling(ratio='4:4:4')
chr_downsample = utils.Downsampling(ratio='4:2:0')
image_block = utils.ImageBlock(block_height=8, block_width=8)
dct2d = utils.DCT2D(norm='ortho')
quantization = utils.Quantization()
zigzagScanning = utils.ZigzagScanning()
rle = utils.RLE()
entropy = utils.Entropy()
###############################################################################
# Preprocess
###############################################################################
# Read raw image file as array
# Generate random pixel values
raw = rawpy.imread(os.path.join('images', 'Nikon-D3500-Shotkit-4.NEF'))

    




In [ ]:
rgb_img = raw.postprocess()


In [ ]:
rgb_img

array([[[186, 148, 162],
        [189, 147, 163],
        [190, 150, 161],
        ...,
        [115,  94, 104],
        [120,  90, 105],
        [120,  87, 106]],

       [[185, 149, 162],
        [184, 151, 162],
        [183, 154, 160],
        ...,
        [111,  92, 104],
        [112,  92, 105],
        [112,  93, 105]],

       [[184, 152, 161],
        [180, 156, 160],
        [177, 154, 159],
        ...,
        [106,  91, 106],
        [104,  95, 104],
        [103,  99, 103]],

       ...,

       [[107,  85,  78],
        [110,  85,  78],
        [112,  84,  77],
        ...,
        [113,  76,  70],
        [115,  74,  70],
        [114,  80,  67]],

       [[100,  85,  79],
        [107,  85,  79],
        [113,  84,  80],
        ...,
        [113,  79,  66],
        [111,  78,  68],
        [111,  79,  69]],

       [[101,  83,  80],
        [107,  84,  80],
        [113,  83,  82],
        ...,
        [113,  80,  63],
        [111,  80,  67],
        [110,  79,  70]]

In [ ]:
# Colorspace transform (RGB -> YCrCb)
ycc_img = cv2.cvtColor(rgb_img, cv2.COLOR_RGB2YCrCb)


In [ ]:
ycc_img

array([[[161, 146, 129],
        [161, 148, 129],
        [163, 147, 127],
        ...,
        [101, 138, 130],
        [101, 142, 130],
        [ 99, 143, 132]],

       [[161, 145, 129],
        [162, 144, 128],
        [163, 142, 126],
        ...,
        [ 99, 137, 131],
        [ 99, 137, 131],
        [100, 137, 131]],

       [[163, 143, 127],
        [164, 139, 126],
        [161, 139, 127],
        ...,
        [ 97, 134, 133],
        [ 99, 132, 131],
        [101, 129, 129]],

       ...,

       [[ 91, 139, 121],
        [ 92, 141, 120],
        [ 92, 142, 120],
        ...,
        [ 86, 147, 119],
        [ 86, 149, 119],
        [ 89, 146, 116]],

       [[ 89, 136, 122],
        [ 91, 139, 121],
        [ 92, 143, 121],
        ...,
        [ 88, 146, 116],
        [ 87, 145, 117],
        [ 87, 145, 118]],

       [[ 88, 137, 123],
        [ 90, 140, 122],
        [ 92, 143, 122],
        ...,
        [ 88, 146, 114],
        [ 88, 144, 116],
        [ 87, 144, 118]]

In [ ]:
# Center
ycc_img = ycc_img.astype(int)-128

In [ ]:
ycc_img

array([[[ 33,  18,   1],
        [ 33,  20,   1],
        [ 35,  19,  -1],
        ...,
        [-27,  10,   2],
        [-27,  14,   2],
        [-29,  15,   4]],

       [[ 33,  17,   1],
        [ 34,  16,   0],
        [ 35,  14,  -2],
        ...,
        [-29,   9,   3],
        [-29,   9,   3],
        [-28,   9,   3]],

       [[ 35,  15,  -1],
        [ 36,  11,  -2],
        [ 33,  11,  -1],
        ...,
        [-31,   6,   5],
        [-29,   4,   3],
        [-27,   1,   1]],

       ...,

       [[-37,  11,  -7],
        [-36,  13,  -8],
        [-36,  14,  -8],
        ...,
        [-42,  19,  -9],
        [-42,  21,  -9],
        [-39,  18, -12]],

       [[-39,   8,  -6],
        [-37,  11,  -7],
        [-36,  15,  -7],
        ...,
        [-40,  18, -12],
        [-41,  17, -11],
        [-41,  17, -10]],

       [[-40,   9,  -5],
        [-38,  12,  -6],
        [-36,  15,  -6],
        ...,
        [-40,  18, -14],
        [-40,  16, -12],
        [-41,  16, -10]]

In [ ]:
# Downsampling
Y = lum_downsample(ycc_img[:,:,0])
Cr = chr_downsample(ycc_img[:,:,1])
Cb = chr_downsample(ycc_img[:,:,2])
ycc_img = np.stack((Y, Cr, Cb), axis=2)

In [ ]:
Y

array([[ 33,  33,  35, ..., -27, -27, -29],
       [ 33,  34,  35, ..., -29, -29, -28],
       [ 35,  36,  33, ..., -31, -29, -27],
       ...,
       [-37, -36, -36, ..., -42, -42, -39],
       [-39, -37, -36, ..., -40, -41, -41],
       [-40, -38, -36, ..., -40, -40, -41]])

In [ ]:
Y[0].size

6016

In [ ]:
Cr[0].size

6016

In [ ]:
Cb.size

24160256

In [ ]:
ycc_img

array([[[ 33,  18,   1],
        [ 33,  18,   1],
        [ 35,  17,  -1],
        ...,
        [-27,   9,   3],
        [-27,  12,   3],
        [-29,  12,   3]],

       [[ 33,  18,   1],
        [ 34,  18,   1],
        [ 35,  17,  -1],
        ...,
        [-29,   9,   3],
        [-29,  12,   3],
        [-28,  12,   3]],

       [[ 35,  13,  -2],
        [ 36,  13,  -2],
        [ 33,  13,  -1],
        ...,
        [-31,   7,   5],
        [-29,   4,   2],
        [-27,   4,   2]],

       ...,

       [[-37,  14,  -7],
        [-36,  14,  -7],
        [-36,  13,  -8],
        ...,
        [-42,  18,  -9],
        [-42,  18, -11],
        [-39,  18, -11]],

       [[-39,  10,  -6],
        [-37,  10,  -6],
        [-36,  13,  -6],
        ...,
        [-40,  19, -12],
        [-41,  16, -11],
        [-41,  16, -11]],

       [[-40,  10,  -6],
        [-38,  10,  -6],
        [-36,  13,  -6],
        ...,
        [-40,  19, -12],
        [-40,  16, -11],
        [-41,  16, -11]]

In [ ]:
# Create 8x8 blocks
blocks, indices = image_block.forward(ycc_img)

In [ ]:
blocks.size

72480768

In [ ]:
indices.size

3397536

In [ ]:
def process_block(block, index):
    
    #Prediction  -> Prediction error
    
    # DCT
    encoded = dct2d.forward(block)
    if index[2] == 0:
        channel_type = 'lum'
    else:
        channel_type = 'chr'
        
    # Quantization
    encoded = quantization.forward(encoded, channel_type)
    
    # RLE + zigzag scanning
    encoded = zigzagScanning.forward(encoded)
    encoded = rle.forward(encoded)
    # Entropy coding (Arithmetic)
    #encoded, prob = entropy.forward(encoded)
    

    # Reverse Entropy coding (Arithmetic)
    #decoded = entropy.backward(encoded, prob)
    decoded = rle.backward(encoded)
    # Reverse RLE + zigzag scanning
    decoded = zigzagScanning.backward(decoded)
    # Dequantization
    decoded = quantization.backward(decoded, channel_type)
    
    # Reverse DCT
    compressed = dct2d.backward(decoded)
    return compressed

    #Reverse Prediction 

In [ ]:
compressed = []
for i in range(0,int(blocks.size/64)-1):
  compressed.append(process_block(blocks[i],indices[i]))

UnboundLocalError: cannot access local variable 'decoded' where it is not associated with a value

In [ ]:
ycc_img_compressed = image_block.backward(compressed, indices)

In [ ]:
ycc_img_compressed = (ycc_img_compressed+128).astype('uint8')

In [ ]:
rgb_img_compressed = cv2.cvtColor(ycc_img_compressed, cv2.COLOR_YCrCb2RGB)

In [ ]:
Image.fromarray(rgb_img_compressed).save(os.path.join('images', 'result.jpeg'))