In [5]:
import rawpy
import cv2
from PIL import Image
import numpy as np
from multiprocessing.pool import Pool
import utils
import os


###############################################################################
# Instantiation
###############################################################################
lum_downsample = utils.Downsampling(ratio='4:4:4')
chr_downsample = utils.Downsampling(ratio='4:2:0')
image_block = utils.ImageBlock(block_height=8, block_width=8)
dct2d = utils.DCT2D(norm='ortho')
quantization = utils.Quantization()
zigzagScanning = utils.ZigzagScanning()
rle = utils.RLE()
entropy = utils.Entropy()
###############################################################################
# Preprocess
###############################################################################
# Read raw image file as array
# Generate random pixel values
raw = rawpy.imread(os.path.join('images', 'Nikon-D3500-Shotkit-4.NEF'))

    




In [6]:
rgb_img = raw.postprocess()


In [7]:
rgb_img.shape

(4016, 6016, 3)

In [8]:
# Colorspace transform (RGB -> YCrCb)
ycc_img = cv2.cvtColor(rgb_img, cv2.COLOR_RGB2YCrCb)


In [9]:
ycc_img

array([[[161, 146, 129],
        [161, 148, 129],
        [163, 147, 127],
        ...,
        [101, 138, 130],
        [101, 142, 130],
        [ 99, 143, 132]],

       [[161, 145, 129],
        [162, 144, 128],
        [163, 142, 126],
        ...,
        [ 99, 137, 131],
        [ 99, 137, 131],
        [100, 137, 131]],

       [[163, 143, 127],
        [164, 139, 126],
        [161, 139, 127],
        ...,
        [ 97, 134, 133],
        [ 99, 132, 131],
        [101, 129, 129]],

       ...,

       [[ 91, 139, 121],
        [ 92, 141, 120],
        [ 92, 142, 120],
        ...,
        [ 86, 147, 119],
        [ 86, 149, 119],
        [ 89, 146, 116]],

       [[ 89, 136, 122],
        [ 91, 139, 121],
        [ 92, 143, 121],
        ...,
        [ 88, 146, 116],
        [ 87, 145, 117],
        [ 87, 145, 118]],

       [[ 88, 137, 123],
        [ 90, 140, 122],
        [ 92, 143, 122],
        ...,
        [ 88, 146, 114],
        [ 88, 144, 116],
        [ 87, 144, 118]]

In [10]:
# Center
ycc_img = ycc_img.astype(int)-128

In [11]:
ycc_img

array([[[ 33,  18,   1],
        [ 33,  20,   1],
        [ 35,  19,  -1],
        ...,
        [-27,  10,   2],
        [-27,  14,   2],
        [-29,  15,   4]],

       [[ 33,  17,   1],
        [ 34,  16,   0],
        [ 35,  14,  -2],
        ...,
        [-29,   9,   3],
        [-29,   9,   3],
        [-28,   9,   3]],

       [[ 35,  15,  -1],
        [ 36,  11,  -2],
        [ 33,  11,  -1],
        ...,
        [-31,   6,   5],
        [-29,   4,   3],
        [-27,   1,   1]],

       ...,

       [[-37,  11,  -7],
        [-36,  13,  -8],
        [-36,  14,  -8],
        ...,
        [-42,  19,  -9],
        [-42,  21,  -9],
        [-39,  18, -12]],

       [[-39,   8,  -6],
        [-37,  11,  -7],
        [-36,  15,  -7],
        ...,
        [-40,  18, -12],
        [-41,  17, -11],
        [-41,  17, -10]],

       [[-40,   9,  -5],
        [-38,  12,  -6],
        [-36,  15,  -6],
        ...,
        [-40,  18, -14],
        [-40,  16, -12],
        [-41,  16, -10]]

In [12]:
# Downsampling
Y = lum_downsample(ycc_img[:,:,0])
Cr = chr_downsample(ycc_img[:,:,1])
Cb = chr_downsample(ycc_img[:,:,2])
ycc_img = np.stack((Y, Cr, Cb), axis=2)

In [13]:
Y

array([[ 33,  33,  35, ..., -27, -27, -29],
       [ 33,  34,  35, ..., -29, -29, -28],
       [ 35,  36,  33, ..., -31, -29, -27],
       ...,
       [-37, -36, -36, ..., -42, -42, -39],
       [-39, -37, -36, ..., -40, -41, -41],
       [-40, -38, -36, ..., -40, -40, -41]])

In [14]:
Y[0].size

6016

In [15]:
Cr[0].size

6016

In [16]:
Cb.size

24160256

In [17]:
ycc_img

array([[[ 33,  18,   1],
        [ 33,  18,   1],
        [ 35,  17,  -1],
        ...,
        [-27,   9,   3],
        [-27,  12,   3],
        [-29,  12,   3]],

       [[ 33,  18,   1],
        [ 34,  18,   1],
        [ 35,  17,  -1],
        ...,
        [-29,   9,   3],
        [-29,  12,   3],
        [-28,  12,   3]],

       [[ 35,  13,  -2],
        [ 36,  13,  -2],
        [ 33,  13,  -1],
        ...,
        [-31,   7,   5],
        [-29,   4,   2],
        [-27,   4,   2]],

       ...,

       [[-37,  14,  -7],
        [-36,  14,  -7],
        [-36,  13,  -8],
        ...,
        [-42,  18,  -9],
        [-42,  18, -11],
        [-39,  18, -11]],

       [[-39,  10,  -6],
        [-37,  10,  -6],
        [-36,  13,  -6],
        ...,
        [-40,  19, -12],
        [-41,  16, -11],
        [-41,  16, -11]],

       [[-40,  10,  -6],
        [-38,  10,  -6],
        [-36,  13,  -6],
        ...,
        [-40,  19, -12],
        [-40,  16, -11],
        [-41,  16, -11]]

In [18]:
# Create 8x8 blocks
blocks, indices = image_block.forward(ycc_img)

In [19]:
blocks.size

72480768

In [20]:
indices.size

3397536

In [21]:

def process_block(block, index, toEncode_Y, toEncode_CbCr):

    #Prediction  -> Prediction error
    
    # DCT
    encoded = dct2d.forward(block)
    if index[2] == 0:
        channel_type = 'lum'
    else:
        channel_type = 'chr'
        
    # Quantization
    encoded = quantization.forward(encoded, channel_type)
    
    # RLE + zigzag scanning
    encoded = zigzagScanning.forward(encoded)
    encoded = rle.forward(encoded)
    
    assert channel_type in ('lum', 'chr')
        
    if channel_type == 'lum':
        toEncode_Y.append(encoded)
    else:
        toEncode_CbCr.append(encoded)
    
    

    
def reconstruct_blocks(decodedY, decodedCbCr,index):
    reconstructed_frame = []
    if index[2] == 0:
        channel_type = 'lum'
    else:
        channel_type = 'chr'
    
    assert channel_type in ('lum', 'chr')
        
    if channel_type == 'lum':
        decoded = decodedY[0]
        decodedY.pop(0)
    else:
        decoded = decodedCbCr[0]
        decodedCbCr.pop(0)
        
    decoded = rle.backward(decoded)
    # Reverse RLE + zigzag scanning
    decoded = zigzagScanning.backward(decoded)
    # Dequantization
    decoded = quantization.backward(decoded, channel_type)
    
    # Reverse DCT
    reconstructed_block = dct2d.backward(decoded)
    
    reconstructed_frame.append(reconstructed_block)

In [22]:
toEncode_Y = []
toEncode_CbCr = []
for i in range(0,int(blocks.size/64)-1):
  process_block(blocks[i] ,indices[i] ,toEncode_Y ,toEncode_CbCr)
  

[[(17.0, 1), (0.0, 63)],
 [(17.0, 1), (0.0, 63)],
 [(17.0, 1), (-0.0, 63)],
 [(16.0, 1), (0.0, 63)],
 [(16.0, 1), (-1.0, 1), (-0.0, 62)],
 [(16.0, 1), (0.0, 63)],
 [(15.0, 1), (0.0, 63)],
 [(15.0, 1), (-0.0, 63)],
 [(16.0, 1), (-0.0, 63)],
 [(16.0, 1), (-0.0, 63)],
 [(17.0, 1), (-0.0, 63)],
 [(17.0, 1), (0.0, 63)],
 [(17.0, 1), (0.0, 63)],
 [(18.0, 1), (0.0, 63)],
 [(18.0, 1), (0.0, 63)],
 [(18.0, 1), (-0.0, 63)],
 [(18.0, 1), (-0.0, 63)],
 [(18.0, 1), (0.0, 63)],
 [(18.0, 1), (0.0, 63)],
 [(18.0, 1), (-0.0, 63)],
 [(18.0, 1), (0.0, 63)],
 [(19.0, 1), (-0.0, 63)],
 [(18.0, 1), (0.0, 63)],
 [(18.0, 1), (0.0, 63)],
 [(18.0, 1), (-0.0, 63)],
 [(18.0, 1), (0.0, 63)],
 [(18.0, 1), (0.0, 63)],
 [(19.0, 1), (0.0, 63)],
 [(18.0, 1), (0.0, 63)],
 [(19.0, 1), (-0.0, 1), (-1.0, 1), (-0.0, 61)],
 [(19.0, 1), (0.0, 63)],
 [(19.0, 1), (0.0, 63)],
 [(20.0, 1), (-1.0, 1), (0.0, 6), (-1.0, 1), (-0.0, 55)],
 [(21.0, 1), (-0.0, 63)],
 [(22.0, 1), (-0.0, 63)],
 [(23.0, 1), (-1.0, 2), (-0.0, 5), (-1.0, 1),

In [25]:
encodedY, codebookY = entropy.huffman_encoding(toEncode_Y)
encodedCbCr, codebookCbCr= entropy.huffman_encoding(toEncode_CbCr)


In [26]:
compression_ratio = rgb_img.shape[0]*rgb_img.shape[1]*24/(sum(len(word) for word in encodedY)+sum(len(word) for word in encodedCbCr))
compression_ratio

33.04340747867009

In [27]:
decodedY = entropy.huffman_decoding(encodedY, codebookY)
decodedCbCr = entropy.huffman_decoding(encodedCbCr, codebookCbCr)


In [28]:
for i in range(0,int(blocks.size/64)-1):
  reconstruct_frame = reconstr_block(blocks[i],indices[i])

377504

In [37]:
ycc_img_compressed = image_block.backward(compressed, indices)

In [38]:
ycc_img_compressed = (ycc_img_compressed+128).astype('uint8')

In [39]:
rgb_img_compressed = cv2.cvtColor(ycc_img_compressed, cv2.COLOR_YCrCb2RGB)

In [44]:
Image.fromarray(rgb_img_compressed).save(os.path.join('images', 'result.bmp'))